Ejercicio 01: Crea un vector nulo (null vector) que tenga 10 elementos

In [10]:
import numpy as np
np.zeros(10)
array = np.array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Ejercicio 02: Crea un vector de unos que tenga 10 elementos

In [13]:
import numpy as np
np.ones(10)
array = np.array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
print(array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Ejercicio 03: Investiga la función linspace de NumPy y crea un array que contenga 10 elementos


In [21]:
import numpy as np
array = np.linspace(1, 10, 10)
print(array)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]



Ejercicio 04: Busca varias formas de generar un array con números aleatorios y crea un array 1D y dos arrays 2D

In [23]:
array = np.random.rand(1,10)
print(array)

[[0.30679716 0.21796867 0.27255887 0.78737214 0.66072952 0.68837373
  0.65804729 0.78064146 0.70833006 0.27036814]]


In [25]:
array = np.random.randint(2, size=10)
print(array)

[0 1 1 0 1 0 0 1 0 0]


In [6]:
# Genere una matriz de 2 x 4 de enteros entre 0 y 4, ambos incluidos:

import numpy as np
np.random.randint(5, size=(2, 4))
array = np.array([[4, 0, 2, 1], [3, 2, 2, 0]])
print(array)

[[4 0 2 1]
 [3 2 2 0]]


In [8]:
#   Genere una matriz de 1 x 3 con 3 límites superiores diferentes

import numpy as np
np.random.randint(1, [3, 5, 10])
array = np.array([2, 2, 9])
print(array)

[2 2 9]


In [10]:
# Genere una matriz de 1 por 3 con 3 límites inferiores diferentes

import numpy as np
np.random.randint([1, 5, 7], 10)
array = np.array([9, 8, 7])
print(array)

[9 8 7]
