Ejercicio 01: Crea un vector nulo (null vector) que tenga 10 elementos

In [10]:
import numpy as np
np.zeros(10)
array = np.array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Ejercicio 02: Crea un vector de unos que tenga 10 elementos

In [13]:
import numpy as np
np.ones(10)
array = np.array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
print(array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Ejercicio 03: Investiga la función linspace de NumPy y crea un array que contenga 10 elementos


In [21]:
import numpy as np
array = np.linspace(1, 10, 10)
print(array)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]



Ejercicio 04: Busca varias formas de generar un array con números aleatorios y crea un array 1D y dos arrays 2D

In [23]:
array = np.random.rand(1,10)
print(array)

[[0.30679716 0.21796867 0.27255887 0.78737214 0.66072952 0.68837373
  0.65804729 0.78064146 0.70833006 0.27036814]]


In [25]:
array = np.random.randint(2, size=10)
print(array)

[0 1 1 0 1 0 0 1 0 0]


In [6]:
# Genere una matriz de 2 x 4 de enteros entre 0 y 4, ambos incluidos:

import numpy as np
np.random.randint(5, size=(2, 4))
array = np.array([[4, 0, 2, 1], [3, 2, 2, 0]])
print(array)

[[4 0 2 1]
 [3 2 2 0]]


In [8]:
#   Genere una matriz de 1 x 3 con 3 límites superiores diferentes

import numpy as np
np.random.randint(1, [3, 5, 10])
array = np.array([2, 2, 9])
print(array)

[2 2 9]


In [10]:
# Genere una matriz de 1 por 3 con 3 límites inferiores diferentes

import numpy as np
np.random.randint([1, 5, 7], 10)
array = np.array([9, 8, 7])
print(array)

[9 8 7]


In [6]:
# Genere una matriz de 2 por 4 usando la transmisión con dtype de uint8

import numpy as np
np.random.randint([1, 3, 5, 7], [[10], [20]], dtype=np.uint8)
array = np.array([[ 8,  6,  9,  7], [ 1, 16,  9, 12]], dtype=np.uint8)
print(array)

[[ 8  6  9  7]
 [ 1 16  9 12]]


In [9]:
import numpy as np
np.random.randn()
2.1923875335537315
array = np.array(2.1923875335537315)
print(array)

2.1923875335537315


In [10]:
# Matriz de muestras de dos por cuatro de la distribución normal con Media 3 y desviación estándar 2,5:

import numpy as np
3 + 2.5 * np.random.randn(2, 4)
np.array([[-4.49401501,  4.00950034, -1.81814867,  7.29718677], [ 0.39924804,  4.68456316,  4.99394529,  4.84057254]])

array([[-4.49401501,  4.00950034, -1.81814867,  7.29718677],
       [ 0.39924804,  4.68456316,  4.99394529,  4.84057254]])

Ejercicio 05: Crea una matriz (array 2D) identidad de 5x5

In [12]:
import numpy as np
np.eye(5, dtype=int)
np.array([[0, 1, 1, 1, 1], [1, 0, 1, 1, 1], [1, 1, 0, 1, 1], [1, 1, 1, 0, 1], [1, 1, 1, 1, 0]])
np.eye(5, k=0)
np.array([[0, 1, 1, 1, 1], [1, 0, 1, 1, 1], [1, 1, 0, 1, 1], [1, 1, 1, 0, 1], [1, 1, 1, 1, 0]])

array([[0, 1, 1, 1, 1],
       [1, 0, 1, 1, 1],
       [1, 1, 0, 1, 1],
       [1, 1, 1, 0, 1],
       [1, 1, 1, 1, 0]])

Ejercicio 06: Crea una matriz con números aleatorios de 3x2 y calcula el valor mínimo y máximo

In [20]:
import numpy as np
b = np.arange(6).reshape((3,2))
np.array([[0, 1], [2, 3], [4, 5]])


array([[0, 1],
       [2, 3],
       [4, 5]])

In [21]:
np.min(b)

np.int64(0)

In [22]:
np.max(b)

np.int64(5)

Ejercicio 07: Crea un vector con números aleatorios de 30 elementos y calcula la media

In [4]:
import numpy as np
vector_entero = np.random.randint(1, 101, size=30)
media_entero = np.mean(vector_entero)
print(vector_entero)

[39 61 75 89 79 85 90 68 46 77 44 95 43 90 28 90 70 91 87 54 79 23 31 60
 32 54 82 62 67 62]


In [5]:
print(media_entero)

65.1


Ejercicio 08: Convierte la lista [1, 2, 3] y la tupla (1, 2, 3) en arrays

In [7]:
import numpy as np
lista = [1, 2, 3]
tupla = (1, 2, 3)

array_lista = np.array(lista)
array_tupla = np.array(tupla) 

In [9]:
print(array_lista)

[1 2 3]


In [10]:
print(array_tupla)

[1 2 3]


Ejercicio 09: Invierte el vector del ejercicio anterior

In [11]:
import numpy as np
vector_original = np.array([1, 2, 3])

vector_invertido = vector_original[::-1]

print("Vector original:", vector_original)
print("Vector invertido:", vector_invertido)


Vector original: [1 2 3]
Vector invertido: [3 2 1]


Ejercicio 10: Cambia el tamaño de un array aleatorio de dimensiones 5x12 en 12x5

In [14]:
# Ejemplo Copilot
import numpy as np

# Crear un array aleatorio de 5x12
array_original = np.random.rand(5, 12)

# Cambiar la forma a 12x5
array_redimensionado = array_original.reshape(12, 5)

print("Array original (5x12):\n", array_original)
print("\nArray redimensionado (12x5):\n", array_redimensionado)


Array original (5x12):
 [[4.16781435e-01 1.31844378e-01 8.46221768e-01 5.08097691e-01
  3.29473870e-01 6.95731301e-01 4.63992172e-01 8.13058443e-01
  3.49179566e-01 5.18673679e-01 9.50574235e-01 8.66534074e-01]
 [8.44508731e-01 1.87905193e-02 4.36622854e-01 7.03277222e-01
  9.47439877e-01 7.78378719e-01 4.16187415e-01 2.74481638e-01
  6.91513161e-02 7.50709325e-01 8.84313278e-02 1.13971534e-01]
 [2.72862618e-01 4.91892004e-01 3.99515681e-01 8.51261870e-01
  3.98930315e-01 5.66132009e-01 2.13047976e-01 1.72061236e-01
  2.65350997e-01 9.12184672e-01 2.47300209e-01 6.21904964e-01]
 [7.14264405e-04 5.15075248e-01 2.19329034e-01 2.16955534e-01
  1.49600074e-01 3.43216322e-01 8.63174381e-01 6.57105469e-01
  8.34604572e-01 5.46417085e-01 4.42079678e-01 7.01536524e-01]
 [7.58746338e-01 9.06398630e-01 2.74349389e-01 6.71761394e-01
  3.68125184e-01 7.55311284e-01 1.94457037e-01 7.23906212e-01
  7.49451609e-01 2.59189269e-01 1.67503047e-01 6.76204625e-01]]

Array redimensionado (12x5):
 [[4.16781

In [18]:
# Ejemplo de link de Pedro

import numpy as np
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9 , 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25], 
             [26, 27, 28, 29,30], [31, 32, 33, 34, 35], [36, 37, 38, 39, 40], [41, 42, 43, 44, 45], [46, 47, 48, 49,50],
              [51, 52, 53, 54, 55], [56, 57, 58, 59, 60]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]
 [51 52 53 54 55]
 [56 57 58 59 60]]


In [21]:
a.reshape(5, 12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

Ejercicio 11: Convierte la lista [1, 2, 0, 0, 4, 0] en un array y obtén el índice de los elementos que no son cero

In [28]:
import numpy as np
lista = [1, 2, 0, 0, 4, 0]
array = np.array(lista)

indices_no_cero = np.nonzero(array)

print("Array:", array)
print("Índices de elementos no cero:", indices_no_cero[0])


Array: [1 2 0 0 4 0]
Índices de elementos no cero: [0 1 4]


Ejercicio 12: Convierte la lista [0, 5, -1, 3, 15] en un array, multiplica sus valores por -2 y obtén los elementos pares

In [29]:
import numpy as np
lista = [0, 5, -1, 3, 15]
array = np.array(lista)

array_multiplicado = array * -2

# Filtrar los elementos pares
elementos_pares = array_multiplicado[array_multiplicado % 2 == 0]

print("Array original:", array)
print("Array multiplicado por -2:", array_multiplicado)
print("Elementos pares:", elementos_pares)


Array original: [ 0  5 -1  3 15]
Array multiplicado por -2: [  0 -10   2  -6 -30]
Elementos pares: [  0 -10   2  -6 -30]


Ejercicio 13: Crea un vector aleatorio de 10 elementos y ordénalo de menor a mayor

In [35]:
import numpy as np
vector = np.random.randint(1, 40, size = 10)
vector_ordenado = np.sort(vector)

print("vector", vector)
print("vector_ordenado", vector_ordenado)

vector [17 31 33 32  8 10 12  7 37  1]
vector_ordenado [ 1  7  8 10 12 17 31 32 33 37]


Ejercicio 14: Genera dos vectores aleatorios de 8 elementos y aplica las operaciones de suma, resta y multiplicación entre ellos

In [39]:
import numpy as np
a = np.random.randint(1, 10, size = 8)
b = np.random.randint(10, 20, size = 8)

suma = a + b
resta = a - b
multiplicacion = a * b

print("a", a)
print("b", b)
print("suma", suma)
print("resta", resta)
print("multiplicacion", multiplicacion)

a [5 4 9 3 1 8 7 1]
b [10 12 15 14 11 15 19 17]
suma [15 16 24 17 12 23 26 18]
resta [ -5  -8  -6 -11 -10  -7 -12 -16]
multiplicacion [ 50  48 135  42  11 120 133  17]


Ejercicio 15: Convierte la lista [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] en un array y transfórmalo en una matriz con filas de 3 columnas

In [41]:
import numpy as np
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
array = np.array(lista)

# Transformarcion
matriz = array.reshape(-1, 3)

print("lista", lista)
print("array", array)
print("Matriz", matriz)

lista [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
array [ 1  2  3  4  5  6  7  8  9 10 11 12]
Matriz [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
